name: Checkout Repository

on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Enable and Prepare Corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install
      - name: Create new branch with UTC timestamp
        run: |
          BRANCH_NAME=variables_$(date -u +"%Y%m%d%H%M%S")
          git checkout -b "$BRANCH_NAME"
        shell: bash
      - name: Generate CSS Variables
        run: yarn generate
        env:
          FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}
          FIGMA_FILE_ID: ${{ vars.FIGMA_FILE_ID }}
          CSS_OUTPUT_FILE: ${{ vars.CSS_OUTPUT_FILE }}
      - name: Push branch to origin
        run: |
          BRANCH_NAME=$(git branch --show-current)
          git push origin "$BRANCH_NAME"
        shell: bash
